# Generated by Django 3.2.12 on 2022-03-29 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20220329_0214'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='name',
            field=models.CharField(default='test', max_length=100),
        ),
    ]
